apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-observability-rest2
  name: go-observability-rest2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-observability-rest2
  template:
    metadata:
      labels:
        app: go-observability-rest2
    spec:
      containers:
      - image: localhost:5000/jcurtis789-pi/go-observability-rest2:latest
        name: go-observability-rest2
---
apiVersion: v1
kind: Service
metadata:
  name: go-observability-rest2
spec:
  selector:
    app: go-observability-rest2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
